const terminal = document.getElementById('terminal-log');
const userDisplay = document.getElementById('user-display');
const sessionHash = document.getElementById('session-hash');
const canvasOverlay = document.getElementById('viewport-overlay');

let rtcConnection;
let inputChannel;
let currentSessionId = "None";

// 1. Authenticate user profile via open-source Puter network architecture
async function initGeneratorEngine() {
    if (puter.auth.isSignedIn()) {
        const user = await puter.auth.getUser();
        userDisplay.innerText = user.username.toUpperCase();
    } else {
        userDisplay.innerText = "GUEST_USER";
        terminal.innerHTML = "⚠️ Guest Mode Active. Sign in via Puter for full cloud logging persistence.";
    }
}

// 2. The Generation Cycle: Coordinates prompt mechanics using Groq and NVIDIA NIM
async function generateNeuralWorld() {
    const promptText = document.getElementById('worldPrompt').value.trim();
    const selectedGenre = document.getElementById('gameGenre').value;

    if (!promptText) {
        alert("Please describe the reality matrix you wish to manifest.");
        return;
    }

    // Provision an ephemeral Session Tracker Hash for this unique world model iteration
    currentSessionId = "world-" + crypto.randomUUID().split('-')[0];
    sessionHash.innerText = currentSessionId;
    canvasOverlay.innerText = "🌀 Initializing Neural Diffusion Latent Engines...";
    terminal.innerHTML = "⚡ Dispatching world physics parameters to Groq Engine Array...";

    try {
        // Step A: Groq compiles the textual description into raw, structural physics matrices
        const groqEndpoint = "https://api.groq.com/openai/v1/chat/completions";
        const groqPrompt = `Transform this game concept into game logic variables for a neural world model simulation. Concept: "${promptText}". Genre Rule: "${selectedGenre}". Respond ONLY in valid JSON format: {"world_seed": 4070, "physics_gravity": 9.8, "render_style": "photorealistic"}`;

        const groqResponse = await puter.net.fetch(groqEndpoint, {
            method: "POST",
            headers: {
                "Authorization": `Bearer ${ENV_CONFIG.groqKey}`,
                "Content-Type": "application/json"
            },
            body: JSON.stringify({
                model: "mixtral-8x7b-32768",
                messages: [{ role: "user", content: groqPrompt }]
            })
        });

        const groqData = await groqResponse.json();
        const structuralMatrix = JSON.parse(groqData.choices[0].message.content);
        
        terminal.innerHTML = `🟢 Physics matrices mapped (Seed: ${structuralMatrix.world_seed}). Spin-up request dispatched to NVIDIA NIM...`;

        // Save generation metadata metrics directly into the individual's Puter Cloud Store
        await puter.kv.set(`generation:${currentSessionId}`, JSON.stringify({
            prompt: promptText,
            genre: selectedGenre,
            matrix: structuralMatrix,
            timestamp: new Date().toISOString()
        }));

        // Step B: Connect to the interactive generative world stream (NVIDIA Cosmos / Diffusion NIM)
        await connectToNeuralRenderingNIM(structuralMatrix, promptText);

    } catch (err) {
        terminal.innerHTML = `🔴 Matrix Generation Anomaly: ${err.message}`;
        canvasOverlay.innerText = "Generation Halted Due to Parameter Fault";
    }
}

// 3. Connect to the Live Generative Video/3D Framework Stream
async function connectToNeuralRenderingNIM(matrix, seedPrompt) {
    canvasOverlay.innerText = "💠 Streaming Live Next-Frame Probabilities (60fps)...";
    
    rtcConnection = new RTCPeerConnection({
        iceServers: [{ urls: 'stun:stun.l.google.com:19302' }]
    });

    // Create tracking paths to channel raw pointer lock deltas into the AI model's latent weights
    inputChannel = rtcConnection.createDataChannel("latentInputChannel");

    const videoCanvas = document.getElementById('renderingCanvas');
    try { await videoCanvas.requestPointerLock(); } catch (e) {}

    // Track physical mouse look deltas, sending them instantly to control the generation camera angle
    window.addEventListener('mousemove', (e) => {
        if (document.pointerLockElement === videoCanvas && inputChannel.readyState === "open") {
            const buffer = new Float32Array([e.movementX, e.movementY]);
            inputChannel.send(buffer);
        }
    });

    // Capture the synthesized gameplay frames generated by the diffusion world layer
    rtcConnection.ontrack = (event) => {
        videoCanvas.srcObject = event.streams[0];
        canvasOverlay.style.display = "none"; // Hide text overlay once video stream binds successfully
        terminal.innerHTML = `🟢 Simulation Matrix Live! Session ID: ${currentSessionId}`;
    };

    // Forward the streaming offer to your NVIDIA Generative World microservice node
    try {
        const offer = await rtcConnection.createOffer();
        await rtcConnection.setLocalDescription(offer);

        const nimEndpoint = "https://integrate.api.nvidia.com/v1/cosmos/world-simulation";
        const nimResponse = await puter.net.fetch(nimEndpoint, {
            method: "POST",
            headers: {
                "Authorization": `Bearer ${ENV_CONFIG.nvidiaKey}`,
                "Content-Type": "application/json"
            },
            body: JSON.stringify({
                sdp: rtcConnection.localDescription,
                generation_parameters: matrix,
                prompt_context: seedPrompt
            })
        });

        const nimData = await nimResponse.json();
        await rtcConnection.setRemoteDescription(new RTCSessionDescription(nimData.sdp));
    } catch (error) {
        terminal.innerHTML = `🔴 Rendering Stream Failure: ${error.message}`;
    }
}

initGeneratorEngine();
